# Generated by Django 2.2.8 on 2020-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='queryString',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
