# Generated by Django 2.2.8 on 2020-02-12 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200121_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(max_length=255)),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.SmallIntegerField(default=1)),
                ('external_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(to='main.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='products',
        ),
        migrations.DeleteModel(
            name='HomepagePhoto',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
