# Generated by Django 2.2.8 on 2020-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200213_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesegment',
            name='position',
            field=models.SmallIntegerField(default=0),
        ),
    ]
