# Generated by Django 2.2.8 on 2020-02-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200213_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesegment',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesegment',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='main.Product'),
        ),
    ]
