# Generated by Django 2.2.8 on 2020-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200213_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesegment',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='homepagesegment',
            name='position',
        ),
        migrations.AddField(
            model_name='homepagesegment',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
