# Generated by Django 2.2.8 on 2020-04-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200213_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='fa_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
